name: Build & deploy PROD
on:
  push:
    branches:
      - master

jobs:
  build-prod-image:
    name: Build prod image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image record.rat.la:prod-${{ github.sha }}
        uses: docker/build-push-action@v3
        with:
          context: .
          target: prod
          no-cache: true
          push: true
          tags: 1noro/record.rat.la:prod-${{ github.sha }}

  deploy-prod:
    name: Deploy in prod env
    runs-on: ubuntu-latest
    steps:
      - name: Stop & delete current container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_HOST_USER }}
          key: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.PROD_HOST_SSH_PORT }}
          script: |
            docker stop record.rat.la-container
            docker rm record.rat.la-container

      - name: Deploy new version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_HOST_USER }}
          key: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.PROD_HOST_SSH_PORT }}
          script: docker run --rm --name record.rat.la-container -p 8247:80 -d 1noro/record.rat.la:prod-${{ github.sha }}
