name: Public pages updated
on:
  push:
    paths:
      - 'public/pages/**.html'
jobs:
  update-rss:
    name: Update RSS feed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install rss-update.py requirements
        run: pip install -r scripts/rss-update-requirements.txt

      - name: Run rss-update.py
        run: python scripts/rss-update.py

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Check if there are local changes
        shell: bash
        run: |
          # refrescamos los índices de git
          git update-index -q --refresh
          # comprobamos si hay cambios locales
          # test -n <string>: Check if string length is non-zero
          test -n "$(git diff-index --name-only HEAD --)"
        #   echo "##[set-output name=therearelocalchanges;]$(echo $?)"
        # id: local_changes

      - name: Setup git config
        if: ${{ steps.extract_branch.outputs.branch == 1 }}
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit
        run: |
          # Stage the file, commit and push
          git add public/rss.xml
          git commit -m "chore(rss): updated rss.xml"
          git push origin ${{ steps.extract_branch.outputs.branch }}
